---
- name: Create variables in Terraform workspace
  uri:
    url: https://{{terraform_api_url}}/workspaces/{{tf_workspace_id}}/vars
    method: POST
    return_content: yes
    headers:
      Authorization: "Bearer {{terraform_api_token}}"
      Content-Type: 'application/vnd.api+json'
      Host: "{{terraform_host}}"
      Accept: '*/*'
    body:
      data:
        type: "vars"
        attributes: "{{ item }}"
    body_format: json
    status_code: 201
  loop: "{{workspace_vars}}"

